# Generated by Django 5.2.7 on 2025-12-01 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Başvuru Yapan Adı')),
                ('surname', models.CharField(max_length=128, verbose_name='Başvuru Yapan Soyadı')),
                ('phone_number', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('note', models.TextField(blank=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('called', models.BooleanField(default=False)),
                ('plan_option', models.ManyToManyField(blank=True, to='schools.planoption')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('school_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.schoolplan')),
            ],
        ),
    ]
