# Generated by Django 5.2.7 on 2025-12-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='called',
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('yeni', 'Yeni Başvuru'), ('ulasilamadi', 'Ulaşılamadı'), ('gorusuldu', 'Görüşüldü'), ('randevu', 'Randevu Oluşturuldu'), ('kayit', 'Kayıt Yapıldı'), ('olumsuz', 'Olumsuz')], default='yeni', max_length=155),
        ),
    ]
