# Generated by Django 5.2.7 on 2025-12-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_remove_lead_called_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('unreachable', 'Unreachable'), ('contacted', 'Contacted'), ('meeting', 'Meeting'), ('signed', 'Signed'), ('negative', 'Negative')], default='new', max_length=155),
        ),
    ]
