# Generated by Django 5.2.7 on 2026-01-12 12:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_deactive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
