# Generated by Django 5.2.7 on 2026-01-12 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_created_at_lead_is_active_lead_is_deactive_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='is_deactive',
            new_name='is_deleted',
        ),
    ]
