# Generated by Django 5.2.7 on 2025-12-01 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=156, verbose_name='Dil Adı')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Özellik Adı')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=156, verbose_name='Servis Adı')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='İkon Kodu')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Okul Adı')),
                ('slug', models.SlugField(unique=True, verbose_name='URL Yolu')),
                ('description', models.TextField(blank=True, verbose_name='Hakkında')),
                ('school_type', models.CharField(choices=[('ozel', 'Özel Okul / Kolej'), ('devlet', 'Devlet Okulu')], max_length=126, verbose_name='Okul Türü')),
                ('address', models.TextField(verbose_name='Açık Adres')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.city')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.district')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to=settings.AUTH_USER_MODEL)),
                ('features', models.ManyToManyField(blank=True, to='schools.schoolfeature')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='school_images/', verbose_name='Okul Görseli')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Plan Başlığı')),
                ('grade_level', models.CharField(choices=[('kres', 'Kreş'), ('anaokulu', 'Anaokulu'), ('ilkokul', 'İlkokul'), ('ortaokul', 'Ortaokul'), ('lise', 'Lise'), ('universite', 'Üniversite')], max_length=20, verbose_name='Eğitim Kademesi')),
                ('description', models.TextField(blank=True, verbose_name='Ekstra Açıklama')),
                ('cash_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peşin Fiyat')),
                ('installment_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Taksitli Fiyat (Liste Fiyatı)')),
                ('languages', models.ManyToManyField(blank=True, to='schools.language')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='schools.school')),
                ('included_services', models.ManyToManyField(blank=True, to='schools.service', verbose_name='Fiyata Dahil Standart Hizmetler')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Gider Adı')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ücret')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.schoolplan')),
            ],
        ),
        migrations.CreateModel(
            name='PlanOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ek Ücret')),
                ('is_compulsory', models.BooleanField(default=False, verbose_name='Zorunlu mu?')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.schoolplan')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.service')),
            ],
        ),
    ]
