# Generated by Django 5.2.7 on 2025-12-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='lead_limit',
            field=models.PositiveIntegerField(default=0, verbose_name='Öğrenci Kotası'),
        ),
    ]
