# Generated by Django 5.2.7 on 2026-01-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_school_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Enlem'),
        ),
        migrations.AddField(
            model_name='school',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Boylam'),
        ),
        migrations.AddField(
            model_name='school',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='school',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='school',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL Yolu'),
        ),
        migrations.AlterField(
            model_name='schoolplan',
            name='cash_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Peşin Fiyat'),
        ),
        migrations.AlterField(
            model_name='schoolplan',
            name='installment_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taksitli Fiyat (Liste Fiyatı)'),
        ),
    ]
