# Generated by Django 5.2.7 on 2026-01-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_school_latitude_school_longitude_school_max_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='school',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='schoolplan',
            name='cash_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Peşin Fiyat'),
        ),
        migrations.AlterField(
            model_name='schoolplan',
            name='installment_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11, verbose_name='Taksitli Fiyat (Liste Fiyatı)'),
        ),
    ]
